In [1]:
import pandas as pd

In [3]:
rf=pd.read_csv('/content/drive/MyDrive/titanic.csv')

In [5]:
rf

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [8]:
h=rf.groupby('Sex')

In [10]:
h#it will not give the answer because groupby function is used only for aggrgate function

In [12]:
h.describe()

       PassengerId                                                             \
             count        mean         std  min     25%    50%     75%    max
Sex
female       314.0  431.028662  256.846324  2.0  231.75  414.5  641.25  889.0
male         577.0  454.147314  257.486139  1.0  222.00  464.0  680.00  891.0

       Survived            ... Parch        Fare                              \
          count      mean  ...   75%  max  count       mean        std   min
Sex                        ...
female    314.0  0.742038  ...   1.0  6.0  314.0  44.479818  57.997698  6.75
male      577.0  0.188908  ...   0.0  5.0  577.0  25.523893  43.138263  0.00


              25%   50%    75%       max
Sex
female  12.071875  23.0  55.00  512.3292
male     7.895800  10.5  26.55  512.3292

[2 rows x 56 columns]

In [14]:
h.mean()

<ipython-input-14-85ea607f2cfa>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  h.mean()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
Sex,,,,,,,
female,431.028662,0.742038,2.159236,27.915709,0.694268,0.649682,44.479818
male,454.147314,0.188908,2.389948,30.726645,0.429809,0.235702,25.523893

In [16]:
rf.T

,0,1,2,3,4,5,6,7,8,9,...,881,882,883,884,885,886,887,888,889,890
PassengerId,1,2,3,4,5,6,7,8,9,10,...,882,883,884,885,886,887,888,889,890,891
Survived,0,1,1,1,0,0,0,0,1,1,...,0,0,0,0,0,0,1,0,1,0
Pclass,3,1,3,1,3,3,1,3,3,2,...,3,3,2,3,3,2,1,3,1,3
Name,"Braund, Mr. Owen Harris","Cumings, Mrs. John Bradley (Florence Briggs Th...","Heikkinen, Miss. Laina","Futrelle, Mrs. Jacques Heath (Lily May Peel)","Allen, Mr. William Henry","Moran, Mr. James","McCarthy, Mr. Timothy J","Palsson, Master. Gosta Leonard","Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)","Nasser, Mrs. Nicholas (Adele Achem)",...,"Markun, Mr. Johann","Dahlberg, Miss. Gerda Ulrika","Banfield, Mr. Frederick James","Sutehall, Mr. Henry Jr","Rice, Mrs. William (Margaret Norton)","Montvila, Rev. Juozas","Graham, Miss. Margaret Edith","Johnston, Miss. Catherine Helen ""Carrie""","Behr, Mr. Karl Howell","Dooley, Mr. Patrick"
Sex,male,female,female,female,male,male,male,male,female,female,...,male,female,male,male,female,male,female,female,male,male
Age,22.0,38.0,26.0,35.0,35.0,NaN,54.0,2.0,27.0,14.0,...,33.0,22.0,28.0,25.0,39.0,27.0,19.0,NaN,26.0,32.0
SibSp,1,1,0,1,0,0,0,3,0,1,...,0,0,0,0,0,0,0,1,0,0
Parch,0,0,0,0,0,0,0,1,2,0,...,0,0,0,0,5,0,0,2,0,0
Ticket,A/5 21171,PC 17599,STON/O2. 3101282,113803,373450,330877,17463,349909,347742,237736,...,349257,7552,C.A./SOTON 34068,SOTON/OQ 392076,382652,211536,112053,W./C. 6607,111369,370376
Fare,7.25,71.2833,7.925,53.1,8.05,8.4583,51.8625,21.075,11.1333,30.0708,...,7.8958,10.5167,10.5,7.05,29.125,13.0,30.0,23.45,30.0,7.75
Cabin,NaN,C85,NaN,C123,NaN,NaN,E46,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,B42,NaN,C148,NaN
Embarked,S,C,S,S,S,Q,S,S,S,C,...,S,S,S,S,Q,S,S,S,C,Q

In [19]:
h.mean().T

<ipython-input-19-3ec22c4f7a34>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  h.mean().T

Sex              female        male
PassengerId  431.028662  454.147314
Survived       0.742038    0.188908
Pclass         2.159236    2.389948
Age           27.915709   30.726645
SibSp          0.694268    0.429809
Parch          0.649682    0.235702
Fare          44.479818   25.523893

In [20]:
h.describe().T

Sex                    female        male
PassengerId count  314.000000  577.000000
            mean   431.028662  454.147314
            std    256.846324  257.486139
            min      2.000000    1.000000
            25%    231.750000  222.000000
            50%    414.500000  464.000000
            75%    641.250000  680.000000
            max    889.000000  891.000000
Survived    count  314.000000  577.000000
            mean     0.742038    0.188908
            std      0.438211    0.391775
            min      0.000000    0.000000
            25%      0.000000    0.000000
            50%      1.000000    0.000000
            75%      1.000000    0.000000
            max      1.000000    1.000000
Pclass      count  314.000000  577.000000
            mean     2.159236    2.389948
            std      0.857290    0.813580
            min      1.000000    1.000000
            25%      1.000000    2.000000
            50%      2.000000    3.000000
            75%      3.000000    3.000000
            max      3.000000    3.000000
Age         count  261.000000  453.000000
            mean    27.915709   30.726645
            std     14.110146   14.678201
            min      0.750000    0.420000
            25%     18.000000   21.000000
            50%     27.000000   29.000000
            75%     37.000000   39.000000
            max     63.000000   80.000000
SibSp       count  314.000000  577.000000
            mean     0.694268    0.429809
            std      1.156520    1.061811
            min      0.000000    0.000000
            25%      0.000000    0.000000
            50%      0.000000    0.000000
            75%      1.000000    0.000000
            max      8.000000    8.000000
Parch       count  314.000000  577.000000
            mean     0.649682    0.235702
            std      1.022846    0.612294
            min      0.000000    0.000000
            25%      0.000000    0.000000
            50%      0.000000    0.000000
            75%      1.000000    0.000000
            max      6.000000    5.000000
Fare        count  314.000000  577.000000
            mean    44.479818   25.523893
            std     57.997698   43.138263
            min      6.750000    0.000000
            25%     12.071875    7.895800
            50%     23.000000   10.500000
            75%     55.000000   26.550000
            max    512.329200  512.329200